# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('birthday', models.DateField()),
                ('ssn', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('O', 'Other')], max_length=10)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=10)),
                ('blood', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10)),
                ('food', models.CharField(choices=[('M', 'Meat'), ('V', 'Veg')], max_length=10)),
                ('allergy', models.CharField(max_length=100)),
                ('medical', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('mugshot', models.ImageField(upload_to='')),
                ('lifeshot', models.ImageField(upload_to='')),
                ('interests', models.TextField(max_length=1000)),
                ('experiences', models.TextField(max_length=1000)),
                ('motivations', models.TextField(max_length=1000)),
                ('how', models.CharField(choices=[('W', 'Webpage'), ('FB', 'Facebook'), ('F', 'Friends'), ('O', 'Other')], max_length=100)),
                ('group', models.TextField(max_length=1000)),
                ('poor', models.TextField(max_length=1000)),
                ('proof', models.FileField(upload_to='')),
            ],
        ),
    ]
