# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='lifeshot',
            field=models.ImageField(upload_to='uploads/lifeshot/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mugshot',
            field=models.ImageField(upload_to='uploads/mugshot/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='proof',
            field=models.FileField(upload_to='uploads/proof/'),
        ),
    ]
