# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160215_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='poor',
            new_name='special',
        ),
    ]
