# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20160217_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='food',
            field=models.CharField(choices=[('M', '葷'), ('V', '素')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='grade',
            field=models.CharField(choices=[('1', '高一'), ('2', '高二'), ('3', '高三'), ('O', '其他 (請在自介說明')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='group',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='how',
            field=models.CharField(choices=[('W', '上網搜尋'), ('FB', '臉書'), ('F', '朋友'), ('C', '班宣'), ('O', '其他'), ('D', '杜鵑花')], max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='special',
            field=models.BooleanField(),
        ),
    ]
