# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20160429_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=9),
        ),
    ]
